Herobrine:
  
  # Should we ignore players not in survival mode?
  survivalOnly: true
  
  # What is the chance something should happen? (1 in X every time a player moves)
  actionChance: 150000
  
  # This is a more advanced equation to choose events, it may cause lag.
  heavierEquation: false

  # What should his name be?
  entityName: Herobrine
 
  # What messages can he put on the signs he places?
  signMessages:
    - I'm watching.
    - Stop.
    - I'm here.
    - Never forget.
    - Brightness.
    
  # What messages should he say when an altar is lit?
  altarMessages:
    - I am your God!
    - I will always prevail!
    - Never doubt my power!
    - Where is your God now?
    - Water, water, water...
    - Look into my eyes!
    
  # What can he write in the books?
  bookMessages:
    - You.
    - Expect me.
    - You'll just be another victim...
    - One more name on the list.

  # What actions aren't allowed? (Type /hb help ingame to view all actions)
  disallowedActions:
    - ExampleAction
    
  # What worlds are off limits to the plugin?
  disallowedWorlds:
    - ExampleWorld